#include <iostream>
using namespace std;

/*
  Calling a function generally causes a certain overhead (stacking arguments, jumps, etc...), and thus for very short functions, it may be more efficient to simply insert the code of the function where it is called, instead of performing the process of formally calling a function.

    Preceding a function declaration with the inline specifier informs the compiler that inline expansion is preferred over the usual function call mechanism for a specific function. This does not change at all the behavior of a function, but is merely used to suggest the compiler that the code generated by the function body shall be inserted at each point the function is called, instead of being invoked with a regular function call.

    For example, the concatenate function above may be declared inline as:
*/

inline string concatenate(string& a,string& b) {
    return a+b;
}

int main() {
    string s1 = "Md";
    string s2 = "rahat";
    cout<<concatenate(s1,s2)<<endl;
    return 0;
}